baseurl = "http://localhost:1313/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 10
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Xoomworks Technology"
    subtitle = "Hackathon 2020"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Xoomworks Technology"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "agenda"
        name = "Agenda"
        url = "/agenda"
      [[languages.en.menu.main]]
        identifier = "howto"
        name = "How to participate"
        url = "/howto"
      [[languages.en.menu.main]]
        identifier = "rules"
        name = "Rules"
        url = "/rules"
